server:
  port: 8481

spring:
  application:
    name: demo-test
    ###ThymeLeaf相关配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
    prefix: classpath:/templates

logging:
  config: classpath:logback.xml
